//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ServiceModel
{
    public class ClientBase<T>
    {
        private ServiceModel.Channels.Binding binding;
        private ServiceModel.EndpointAddress endpointAddress;

        public ClientBase(ServiceModel.Channels.Binding binding, ServiceModel.EndpointAddress endpointAddress)
        {
            this.binding = binding;
            this.endpointAddress = endpointAddress;
        }

        public object Channel { get; internal set; }
    }
}